import { User, Listing, Category } from "@/types";

export const mockCategories: Category[] = [
  { id: "1", name: "Electronics", slug: "electronics", icon: "Laptop" },
  { id: "2", name: "Furniture", slug: "furniture", icon: "Sofa" },
  { id: "3", name: "Vehicles", slug: "vehicles", icon: "Car" },
  { id: "4", name: "Fashion", slug: "fashion", icon: "Shirt" },
  { id: "5", name: "Books", slug: "books", icon: "Book" },
  { id: "6", name: "Sports", slug: "sports", icon: "Dumbbell" },
  { id: "7", name: "Home Appliances", slug: "home-appliances", icon: "Home" },
  { id: "8", name: "Mobile Phones", slug: "mobile-phones", icon: "Smartphone" },
];

export const mockUser: User = {
  id: "1",
  name: "John Doe",
  email: "john@example.com",
  image: "https://api.dicebear.com/7.x/avatars/svg?seed=John",
  phone: "+91 9876543210",
  location: "Mumbai, Maharashtra",
  createdAt: new Date().toISOString(),
  role: "user",
};

export const mockListings: Listing[] = [
  {
    id: "1",
    title: "iPhone 13 Pro Max - 256GB",
    description:
      "Excellent condition iPhone 13 Pro Max with 256GB storage. Comes with original box and accessories. No scratches, battery health 95%.",
    price: 65000,
    category: "mobile-phones",
    location: "Mumbai, Maharashtra",
    images: [
      "https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1611472173362-3f53dbd65d80?w=800&h=600&fit=crop",
    ],
    userId: "1",
    user: mockUser,
    status: "active",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    views: 234,
  },
  {
    id: "2",
    title: "Wooden Study Table with Chair",
    description:
      "Solid wood study table with matching chair. Perfect for home office or student use. Minor wear and tear.",
    price: 5000,
    category: "furniture",
    location: "Delhi",
    images: [
      "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&h=600&fit=crop",
    ],
    userId: "2",
    user: {
      id: "2",
      name: "Jane Smith",
      email: "jane@example.com",
      image: "https://api.dicebear.com/7.x/avatars/svg?seed=Jane",
      location: "Delhi",
      createdAt: new Date().toISOString(),
      role: "user",
    },
    status: "active",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    views: 112,
  },
  {
    id: "3",
    title: "Honda City 2018 - Diesel",
    description:
      "Well maintained Honda City 2018 model. Single owner, full service history. All documents clear.",
    price: 850000,
    category: "vehicles",
    location: "Bangalore, Karnataka",
    images: [
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop",
    ],
    userId: "3",
    user: {
      id: "3",
      name: "Rajesh Kumar",
      email: "rajesh@example.com",
      image: "https://api.dicebear.com/7.x/avatars/svg?seed=Rajesh",
      location: "Bangalore, Karnataka",
      createdAt: new Date().toISOString(),
      role: "user",
    },
    status: "active",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    views: 567,
  },
  {
    id: "4",
    title: "MacBook Pro M1 - 16GB RAM",
    description:
      "2021 MacBook Pro with M1 chip, 16GB RAM, 512GB SSD. Like new condition with AppleCare+ till 2024.",
    price: 95000,
    category: "electronics",
    location: "Pune, Maharashtra",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=600&fit=crop",
    ],
    userId: "1",
    user: mockUser,
    status: "active",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    views: 345,
  },
  {
    id: "5",
    title: "Nike Air Max Sneakers - Size 10",
    description:
      "Brand new Nike Air Max sneakers in size 10 (US). Never worn, with original box and tags.",
    price: 8999,
    category: "fashion",
    location: "Chennai, Tamil Nadu",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=600&fit=crop",
    ],
    userId: "4",
    user: {
      id: "4",
      name: "Priya Sharma",
      email: "priya@example.com",
      image: "https://api.dicebear.com/7.x/avatars/svg?seed=Priya",
      location: "Chennai, Tamil Nadu",
      createdAt: new Date().toISOString(),
      role: "user",
    },
    status: "active",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    views: 89,
  },
  {
    id: "6",
    title: "LG Washing Machine - 7kg",
    description:
      "Fully automatic LG washing machine, 7kg capacity. 2 years old, working perfectly.",
    price: 12000,
    category: "home-appliances",
    location: "Hyderabad, Telangana",
    images: [
      "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&h=600&fit=crop",
    ],
    userId: "2",
    user: {
      id: "2",
      name: "Jane Smith",
      email: "jane@example.com",
      image: "https://api.dicebear.com/7.x/avatars/svg?seed=Jane",
      location: "Delhi",
      createdAt: new Date().toISOString(),
      role: "user",
    },
    status: "active",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    views: 178,
  },
];
